export const SET_USER_LIST = 'SET_USER_LIST';
export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const SET_SPONSER_LIST = 'SET_SPONSER_LIST';
export const SET_PARTICIPANTS_LIST = 'SET_PARTICIPANTS_LIST';