export const SET_USER_LIST = 'SET_USER_LIST';
export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const SET_SPONSER_LIST = 'SET_SPONSER_LIST';
export const SET_PARTICIPANTS_LIST = 'SET_PARTICIPANTS_LIST';

export const SET_AGE_GROUPS = 'SET_AGE_GROUPS';
export const SET_MEDICAL_CONDITIONS = 'SET_MEDICAL_CONDITIONS';